// Concept cards. `book` holds the QSS definition box word for word (formulas typeset); `back` adds a plain-language
// explanation and a book example. Pages are the printed QSS page numbers.
const r = String.raw;
const K = (id, topics, sec, page, front, book, back, extra = {}) => ({ id, dict: "concept", topics, sec, page, front, book, back, reversible: true, ...extra });
const ex = s => `<p><b>Book example:</b> ${s}</p>`;

export default [
  // ---------- Causality and research designs (Ch 2) ----------
  K("con-experimental", ["causal"], "2.1", 33, "Experimental research",
    r`Experimental research examines how a treatment causally affects an outcome by assigning varying values of the treatment variable to different observations, and measuring their corresponding values of the outcome variable.`,
    r`<p>The researcher <i>assigns</i> the treatment, rather than observing who happens to get it.</p>` + ex(r`The résumé experiment assigned Black- or white-sounding names to otherwise identical résumés and measured callbacks.`)),
  K("con-causal-effect", ["causal"], "2.3", 48, "Causal effect (for one unit)",
    r`For each observation \(i\), we can define the causal effect of a binary treatment \(T_i\) as the difference between two potential outcomes, \(Y_i(1) - Y_i(0)\), where \(Y_i(1)\) represents the outcome that would be realized under the treatment condition \((T_i = 1)\) and \(Y_i(0)\) denotes the outcome that would be realized under the control condition \((T_i = 0)\).`,
    r`<p>The effect for one unit is the difference between what happens with and without the treatment, for that same unit.</p>` + ex(r`Would the same employer have called back if the same résumé carried the name Lakisha instead of Allison?`)),
  K("con-potential-outcomes", ["causal"], "2.3", 47, "Counterfactual and potential outcomes",
    "",
    r`<p>Causal inference compares the <b>factual</b> (what actually happened) with the <b>counterfactual</b> (what would have happened if a key condition were different). The <b>potential outcomes</b> \(Y_i(1)\) and \(Y_i(0)\) are unit \(i\)'s outcome under treatment and under control. Only the one matching the unit's actual treatment is observed; in the book's table 2.3 the other is a "?". Pretreatment characteristics (age, education) are not affected by the treatment.</p>` + ex(r`A state raises its minimum wage and unemployment rises; the counterfactual is that state's unemployment had it <i>not</i> raised the wage, which we never observe.`)),
  K("con-fundamental", ["causal"], "2.3", 48, "Fundamental problem of causal inference",
    r`The fundamental problem of causal inference is that we observe only one of the two potential outcomes, and which potential outcome is observed depends on the treatment status. Formally, the observed outcome \(Y_i\) is equal to \(Y_i(T_i)\).`,
    r`<p>We can never see the same unit both treated and untreated, so individual effects can't be computed; we must infer the missing counterfactuals, which requires assumptions (identification assumptions).</p>` + ex(r`A résumé sent with a Black-sounding name shows \(Y_i(1)\); its callback under a white-sounding name, \(Y_i(0)\), is unknown.`)),
  K("con-immutable", ["causal"], "2.3", 48, "Immutable characteristics; \"no causation without manipulation\"",
    "",
    r`<p>Characteristics like race and gender can't be manipulated, so many scholars think causal questions about them are not answerable: "no causation without manipulation." The résumé study gets around this by manipulating <i>employers' perception</i> of race (through names) rather than race itself.</p>`),
  K("con-sate", ["causal"], "2.4.1", 49, "Sample average treatment effect (SATE)",
    r`The sample average treatment effect (SATE) is defined as the sample average of individual-level causal effects (i.e., \(Y_i(1) - Y_i(0)\)): \[\text{SATE} = \frac{1}{n}\sum_{i=1}^{n}\{Y_i(1) - Y_i(0)\},\] where \(n\) is the sample size, and \(\sum_{i=1}^{n}\) denotes the summation operator from the first observation, \(i = 1\), to the last, \(i = n\).`,
    r`<p>The average of everyone's individual effect in the sample. It is not directly observable (each unit reveals only one potential outcome), but randomization lets the difference-in-means estimate it.</p>`),
  K("con-satt", ["causal"], "2.5.3", 62, "Sample average treatment effect for the treated (SATT)",
    "",
    r`<p>The average causal effect among the <b>treated units only</b>: \(\text{SATT} = \frac{1}{n_1}\sum_{i=1}^{n} T_i\{Y_i(1) - Y_i(0)\}\), where \(T_i\) is the treatment indicator and \(n_1 = \sum_{i=1}^{n} T_i\) is the size of the treatment group. It differs from the SATE, which averages over everyone. Difference-in-differences estimates the SATT, because its counterfactual is built only for the treated group.</p>` + ex(r`The DiD estimate in the minimum-wage study is the effect for New Jersey restaurants, not for restaurants in general.`)),
  K("con-diff-means", ["causal"], "2.4.1", 49, "Difference-in-means estimator",
    "",
    r`<p>Average outcome of the treatment group minus average outcome of the control group. The control group's average stands in for the treated group's missing \(Y(0)\), and vice versa. Under randomization it is a valid (unbiased) estimate of the SATE.</p>` + ex(r`Neighbors-message turnout minus control turnout: 0.378 − 0.297 = 0.081 (8.1 points).`)),
  K("con-rct", ["causal"], "2.4.1", 50, "Randomized controlled trial (RCT)",
    r`In a randomized controlled trial (RCT), each unit is randomly assigned either to the treatment or control group. The randomization of treatment assignment guarantees that the average difference in outcome between the treatment and control groups can be attributed solely to the treatment, because the two groups are on average identical to each other in all pretreatment characteristics.`,
    r`<p>Random assignment balances observed <i>and unobserved</i> characteristics on average, so the only systematic difference between the groups is the treatment. That's why the RCT is the "gold standard."</p>` + ex(r`The social pressure experiment randomly assigned Michigan voters to four get-out-the-vote mailings or none.`)),
  K("con-balance", ["causal"], "2.4.2", 54, "Balance check",
    "",
    r`<p>Compare the groups' averages of <b>pretreatment</b> variables. If randomization worked, the differences should be small. Big differences suggest a problem with assignment, or (in small samples) chance imbalance.</p>` + ex(r`<code>tapply(social$age, social$messages, mean)</code> gives about 49.7–49.9 in every group; prior turnout and household size are similar too.`)),
  K("con-internal", ["causal"], "2.4.1", 50, "Internal validity",
    r`The main advantage of randomized controlled trials (RCTs) is their improved internal validity—the extent to which causal assumptions are satisfied in the study.`,
    r`<p>Can we trust the causal conclusion <i>for the units in this study</i>? RCTs score high; observational studies are threatened by confounding.</p>`),
  K("con-external", ["causal"], "2.4.1", 50, "External validity",
    r`One weakness of RCTs, however, is the potential lack of external validity—the extent to which the conclusions can be generalized beyond a particular study.`,
    r`<p>Do the results generalize to other people, places, and settings? Threats: convenience samples (sample selection bias), artificial lab settings, unrealistic interventions. Field experiments help. Observational studies often have stronger external validity.</p>`),
  K("con-hawthorne", ["causal"], "2.4.2", 52, "Hawthorne effect",
    r`The Hawthorne effect refers to the phenomenon where study subjects behave differently because they know they are being observed by researchers.`,
    r`<p>Being studied can itself change behavior, separate from the treatment's content.</p>` + ex(r`The social pressure study added a "YOU ARE BEING STUDIED!" mailing (+2.6 points) to separate the effect of being observed from the naming-and-shaming Neighbors message (+8.1).`)),
  K("con-observational", ["causal"], "2.5", 54, "Observational study",
    "",
    r`<p>The researcher does not intervene; they observe naturally occurring treatment and outcomes. It's used when randomization is unethical or impossible. Internal validity is weaker (possible selection bias), but external validity is often stronger because the treatment happens in a real-world setting.</p>` + ex(r`New Jersey raised its minimum wage; researchers compared its fast-food restaurants with Pennsylvania's.`)),
  K("con-confounder", ["causal"], "2.5.2", 58, "Confounder and confounding bias",
    r`A pretreatment variable that is associated with both the treatment and the outcome variables is called a confounder and is a source of confounding bias in the estimation of the treatment effect.`,
    r`<p>A confounder makes the treated and control groups differ for reasons other than the treatment, so a simple comparison mixes the treatment's effect with the confounder's.</p>` + ex(r`A competing low-wage industry in NJ but not PA could raise NJ's full-time employment regardless of the minimum wage.`)),
  K("con-selection-bias", ["causal"], "2.5.2", 58, "Selection bias (self-selection)",
    "",
    r`<p>The book: "Confounding bias due to self-selection into the treatment group is called selection bias." When people (or states) choose their own treatment, those who select in may differ from those who don't in observed and unobserved ways. This is why "association does not necessarily imply causation."</p>` + ex(r`NJ politicians chose to raise the minimum wage, perhaps for economic reasons also related to employment.`)),
  K("con-statistical-control", ["causal"], "2.5.2", 60, "Statistical control",
    r`Confounding bias can be reduced through statistical control. For example, we can use the method of subclassification by comparing treated and control units which have an identical value of a confounding variable.`,
    r`<p>Adjusting for measured confounders with statistical procedures. It can't rule out confounding by unmeasured variables.</p>`),
  K("con-subclassification", ["causal"], "2.5.2", 60, "Subclassification",
    "",
    r`<p>Compare treated and control units <b>within</b> subsets that share the same value of a confounder, so that variable can't explain the difference. Further subclassify on more variables for a finer comparison. Stable estimates across subclasses build confidence.</p>` + ex(r`Compare only Burger Kings in NJ vs PA (0.036), then only Burger Kings in northern and southern NJ (0.031): similar to the overall 0.048.`)),
  K("con-cross-section", ["causal"], "2.5.1", 55, "Cross-section comparison design",
    "",
    r`<p>Compare treated and control units <b>after</b> treatment, at one point in time. It assumes the two groups are comparable on everything related to the outcome except the treatment, so it is vulnerable to any confounder that differs between groups.</p>` + ex(r`NJ minus PA full-time employment share after the increase: +0.048.`)),
  K("con-before-after", ["causal"], "2.5.3", 61, "Before-and-after design",
    r`The before-and-after design examines how the outcome variable changed from the pretreatment period to the posttreatment period for the same set of units. The design is able to adjust for any confounding factor that is specific to each unit but does not change over time. However, the design does not address possible bias due to time-varying confounders.`,
    r`<p>Compares the treated units with themselves before treatment. A time trend (e.g. an improving economy) gets wrongly credited to the treatment.</p>` + ex(r`NJ's full-time share after minus before: +0.024.`)),
  K("con-did", ["causal"], "2.5.3", 62, "Difference-in-differences (DiD) design",
    r`The difference-in-differences (DiD) design uses the following estimate of the sample average treatment effect for the treated (SATT): \[\text{DiD estimate} = \underbrace{(\bar{Y}_{\text{treated}}^{\text{after}} - \bar{Y}_{\text{treated}}^{\text{before}})}_{\text{difference for the treatment group}} - \underbrace{(\bar{Y}_{\text{control}}^{\text{after}} - \bar{Y}_{\text{control}}^{\text{before}})}_{\text{difference for the control group}}.\] The assumption is that the counterfactual outcome for the treatment group has a time trend parallel to that of the control group.`,
    r`<p>Uses the control group's change over time to estimate the trend the treated group would have followed without treatment. It needs before and after data for both groups and removes both time-invariant differences between groups and common time trends.</p>` + ex(r`NJdiff − PAdiff = 0.024 − (−0.038) = 0.062.`)),
  K("con-parallel-trends", ["causal"], "2.5.3", 63, "Parallel trends assumption",
    "",
    r`<p>DiD's key assumption: absent treatment, the treated group's outcome would have changed by the same amount as the control group's. It can't be verified, because the treated group's counterfactual trend is unobserved, but data from earlier periods showing parallel movement make it more credible. If trends aren't parallel, DiD is biased.</p>`),

  // ---------- Descriptive statistics ----------
  K("con-median", ["describe"], "2.6.1", 64, "Median vs. mean",
    r`The median is less sensitive to outliers than the mean and hence is a more robust measure of the center of a distribution.`,
    r`<p>The median is the middle value of the sorted data (average of the two middle values if n is even). The mean uses every value's size, so extreme values pull it.</p>` + ex(r`Median of {1, 3, 4, 10, 82} is 4; the mean is 20.`)),
  K("con-quantiles", ["describe"], "2.6.1", 66, "Quantiles",
    r`Quantiles represent a set of data values that divide observations into a certain number of equally sized groups. They include quartiles (dividing the observations into 4 groups) and percentiles (100 groups).`,
    r`<p>Others: terciles (3 groups), quintiles (5), deciles (10). Compute with <code>quantile(x, probs = )</code>.</p>` + ex(r`Deciles of NJ wages after the increase show 5.05 from the 10th to the 80th percentile: bunching at the new minimum.`)),
  K("con-quartiles", ["describe"], "2.6.1", 66, "Quartiles",
    r`25th percentile = lower quartile; 50th percentile = median; 75th percentile = upper quartile.`,
    r`<p>The three values that split sorted data into four equal-sized groups. <code>summary()</code> reports them as 1st Qu., Median, 3rd Qu.</p>`),
  K("con-iqr", ["describe"], "2.6.1", 66, "Interquartile range (IQR)",
    r`The difference between the upper and lower quartiles is called the interquartile range and measures the spread of a distribution.`,
    r`<p>The spread of the middle 50% of the data; unlike the range, it isn't driven by one extreme value. An IQR of 0 means the middle half of values are identical.</p>` + ex(r`NJ wages: IQR 0.62 before the increase, 0 after, because most restaurants paid exactly $5.05.`)),
  K("con-rms", ["describe"], "2.6.2", 66, "Root mean square (RMS)",
    "",
    r`<p>Square each entry, take the mean, then the square root: \(\sqrt{\frac{1}{n}\sum x_i^2}\). It measures average <b>magnitude</b>, ignoring sign. The mean of {−2, −1, 0, 1, 2} is 0 but its RMS is \(\sqrt{2}\). SD is the RMS of deviations from the mean; RMSE is the RMS of prediction errors.</p>` + ex(r`NJ's change in full-time share: mean 0.024 but RMS 0.30, so individual restaurants changed a lot in both directions.`)),
  K("con-sd", ["describe"], "2.6.2", 68, "Standard deviation",
    r`The sample standard deviation measures the average deviation from the mean and is defined as \[\text{standard deviation} = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2} \quad\text{or}\quad \sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2},\] where \(\bar{x}\) represents the sample mean, i.e., \(\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i\) and \(n\) is the sample size. Few data points lie outside 2 or 3 standard deviations away from the mean. The square of the standard deviation is called the variance.`,
    r`<p>A typical distance of a value from the mean, in the variable's own units. R's <code>sd()</code> uses n − 1; with enough data the two versions barely differ.</p>`),
  K("con-variance", ["describe"], "2.6.2", 68, "Variance",
    "",
    r`<p>The square of the standard deviation: the average squared deviation from the mean. It is harder to interpret (squared units) but useful analytically. R's <code>var()</code> uses n − 1.</p>` + ex(r`<code>var(minwageNJ$fullPropBefore)</code> = 0.053, the square of its SD 0.230.`)),
  K("con-binary-mean", ["describe", "rbasics"], "2.1", 36, "Mean of a binary (0/1) variable",
    "",
    r`<p>The book: "the sample mean of a binary variable equals the sample proportion of 1s." So <code>mean()</code> of a 0/1 (or TRUE/FALSE) variable gives a rate, and <code>sum()</code> gives a count.</p>` + ex(r`<code>mean(resume$call)</code> = 0.0805, the overall callback rate.`)),
  K("con-pct-points", ["describe"], "2.1", 36, "Percent vs. percentage points",
    "",
    r`<p>The difference between two percentages is in <b>percentage points</b>. A relative change is in <b>percent</b>.</p>` + ex(r`Callback rates 6.4% (Black names) and 9.7% (white names) differ by 3.2 percentage points; the Black rate is about 33% lower in relative terms.`)),

  // ---------- Sampling and measurement (Ch 3) ----------
  K("con-survey-sampling", ["sampling"], "3.4", 89, "Survey sampling (population, sample, census)",
    "",
    r`<p>Survey sampling selects a subset of a target <b>population</b>, the <b>sample</b>, to learn about the population's features. A <b>census</b> instead enumerates every member. A random sample of about 1,000 can describe 200+ million adults.</p>`),
  K("con-sampling-frame", ["sampling"], "3.4.1", 90, "Sampling frame",
    "",
    r`<p>The complete list of potential respondents from which a sample is drawn. Lists of phones, addresses, or emails are often incomplete and miss certain kinds of people, causing sample selection bias.</p>` + ex(r`Random digit dialing misses people without phones and over-samples people with several numbers.`)),
  K("con-srs", ["sampling"], "3.4.1", 90, "Simple random sampling (SRS)",
    r`Simple random sampling (SRS) is the most basic form of probability sampling, which avoids sample selection bias by randomly choosing units from a population. Under SRS, the predetermined number of units is randomly selected from a target population without replacement, where each unit has an equal probability of being selected. The resulting sample is representative of the population in terms of any observed and unobserved characteristics.`,
    r`<p>"Representative" means representative on average across repeated samples, just as randomization balances groups on average in an RCT.</p>`),
  K("con-probability-sampling", ["sampling"], "3.4.1", 89, "Probability sampling",
    "",
    r`<p>Sampling in which every unit of the target population has a <b>known, nonzero</b> probability of selection. SRS is the simplest kind (equal probabilities); multistage cluster sampling is another (probabilities known only approximately).</p>`),
  K("con-quota", ["sampling"], "3.4.1", 89, "Quota sampling (and why it fails)",
    "",
    r`<p>Interview people until fixed quotas match the population on chosen traits (age, gender, education...). It can match <i>observed</i> traits while differing on <i>unobserved</i> ones, and interviewers choose whom to approach. This is the same problem as observational studies. Quota-based polls predicted "Dewey defeats Truman" in 1948.</p>`),
  K("con-cluster", ["sampling"], "3.4.1", 91, "Multistage cluster sampling",
    "",
    r`<p>Sample large units first, then smaller units within them. It is used when no list of individuals exists and to save travel cost.</p>` + ex(r`The Afghanistan survey sampled districts, then villages, then households, then a male respondent.`)),
  K("con-sample-selection-bias", ["sampling", "causal"], "2.4.1 / 3.4.1", 50, "Sample selection bias",
    "",
    r`<p>A sample that is not representative of the target population, e.g. a convenience sample of willing subjects. It threatens <b>external validity</b> (generalizing), not the internal comparison. Probability sampling (e.g. SRS) avoids it.</p>`),
  K("con-log", ["sampling"], "3.4.1", 92, "Natural logarithmic transformation",
    r`The natural logarithmic transformation is often used to correct the skewness of variables such as income and population that have a small number of observations with extremely large or small positive values. The natural logarithm is the logarithm with base \(e\), which is a mathematical constant approximately equal to 2.7182, and defined as \(y = \log_e x\). It is the inverse function of the exponential function, so \(x = e^y\).`,
    r`<p>Logs compress large values, making skewed distributions readable; they're defined only for positive numbers.</p>` + ex(r`<code>boxplot(log(population) ~ village.surveyed, ...)</code> compares sampled and nonsampled villages' populations.`)),
  K("con-unit-nonresponse", ["sampling"], "3.4.2", 94, "Unit nonresponse",
    r`Unit nonresponse refers to a case in which a potential respondent refuses to participate in a survey. … Both nonresponses can result in biased inferences if those who respond to a question are systematically different from those who do not.`,
    r`<p>Refusing the <i>whole</i> survey.</p>` + ex(r`In Afghanistan, 343 of 3,097 contacted men refused (an 11% refusal rate).`)),
  K("con-item-nonresponse", ["sampling"], "3.4.2", 94, "Item nonresponse",
    r`Item nonresponse occurs when a respondent who agreed to participate refuses to answer a particular question. Both nonresponses can result in biased inferences if those who respond to a question are systematically different from those who do not.`,
    r`<p>Skipping a <i>particular</i> question.</p>` + ex(r`Nonresponse to the Taliban-violence question was highest in Helmand and Uruzgan, the most violent provinces: systematic, not random.`)),
  K("con-listwise", ["sampling"], "3.2", 79, "Missing data and listwise deletion",
    "",
    r`<p>R codes missing values as <code>NA</code>. <b>Listwise deletion</b> (<code>na.omit()</code> on a data frame) drops every observation with at least one missing value, discarding the questions that person <i>did</i> answer, and it can bias results if missingness is systematic.</p>` + ex(r`na.omit(afghan) keeps 2,554 rows, though 2,600 answered the income question.`)),
  K("con-social-desirability", ["sampling"], "3.4.2", 94, "Social desirability bias",
    "",
    r`<p>Respondents give the answer they think is socially acceptable instead of the truth: misreporting. It affects sensitive topics: turnout (non-voters claim they voted), corruption, illegal behavior, racial prejudice, sexual activity.</p>`),
  K("con-list-experiment", ["sampling"], "3.4.2", 95, "List experiment (item count technique)",
    "",
    r`<p>Randomly split respondents. The control group hears a list of non-sensitive items; the treatment group hears the same list plus the sensitive item. Each respondent reports only <i>how many</i> items apply. The difference in mean counts estimates the proportion for the sensitive item, and aggregation protects anonymity.</p>` + ex(r`Adding "Foreign Forces" estimated about 5% support for the ISAF.`)),
  K("con-floor-ceiling", ["sampling"], "3.4.2", 95, "Floor and ceiling effects",
    "",
    r`<p>In a list experiment's treatment group, answering 0 (floor) or the maximum (ceiling) reveals the respondent's answer to the sensitive item, so anonymity fails and respondents may misreport.</p>` + ex(r`No one in the Taliban list group answered 0 or 4, perhaps to avoid being identified.`)),
  K("con-randomized-response", ["sampling"], "3.4.2", 96, "Randomized response technique",
    "",
    r`<p>Respondents privately roll a die: answer "yes" on 1, "no" on 6, and honestly on 2–5. No individual answer reveals anything, but because the probabilities are known, the share of honest "yes" answers can be recovered in aggregate.</p>`),
  K("con-density", ["describe", "sampling"], "3.3.2", 83, "Histogram density",
    r`A histogram divides the data into bins where the area of each bin represents the proportion of observations that fall within the bin. The height of each bin represents density, which is equal to the proportion of observations within each bin divided by the width of the bin. A histogram approximates the distribution of a variable.`,
    r`<p>Density is "proportion per unit of the x-axis," so it can exceed 1; bin <i>areas</i> sum to 1. Density lets you compare distributions with different sample sizes.</p>`),
  K("con-latent", ["sampling"], "3.5", 96, "Latent concepts and measurement models",
    "",
    r`<p>A <b>latent</b> concept (ideology, ability) can't be observed directly. A <b>measurement model</b> links it to observed behavior so it can be inferred.</p>` + ex(r`Inferring legislators' ideology (DW-NOMINATE scores) from their roll-call votes.`)),
  K("con-ideal-point", ["sampling"], "3.5", 97, "Ideal points and the spatial voting model",
    "",
    r`<p>Each legislator has an <b>ideal point</b> in an ideological space (e.g. economic and racial liberalism–conservatism). They vote for whichever of the <b>status quo</b> and the <b>proposal</b> is closer to their ideal point. Unanimous votes carry no information about ideology; divided votes do.</p>`),
  K("con-irt", ["sampling"], "3.5", 97, "Item response theory",
    "",
    r`<p>The same measurement idea applied to tests (SAT, GRE): student ability plays the role of the ideal point, and each question's difficulty is estimated too, so you can pick questions that separate stronger from weaker students.</p>`),

  // ---------- Correlation and clustering ----------
  K("con-zscore", ["correlation"], "3.6.2", 104, "z-score",
    r`The z-score of the \(i\)th observation of a variable \(x\) measures the number of standard deviations an observation is above or below the mean. It is defined as \[\text{z-score of } x_i = \frac{x_i - \bar{x}}{S_x},\] where \(\bar{x}\) and \(S_x\) are the mean and standard deviation of \(x\), respectively. The z-score, as a measure of deviation from the mean, is not sensitive to how the variable is scaled and/or shifted.`,
    r`<p>z = 1.5 means 1.5 SDs above the mean. Changing units (\(ax + b\), with \(a &gt; 0\)) leaves z-scores unchanged; a negative \(a\) flips their sign.</p>`),
  K("con-correlation", ["correlation"], "3.6.2", 105, "Correlation",
    r`Correlation (correlation coefficient) measures the degree to which two variables are associated with each other. It is defined as \[\text{correlation of } x \text{ and } y = \frac{1}{n}\sum_{i=1}^{n}\frac{x_i - \bar{x}}{S_x}\times\frac{y_i - \bar{y}}{S_y},\] where \(\bar{x}\) and \(\bar{y}\) are the means and \(S_x\) and \(S_y\) are the standard deviations for variables \(x\) and \(y\), respectively. Correlation ranges from −1 to 1 and is not sensitive to how a variable is scaled and/or shifted.`,
    r`<p>The average product of z-scores. It's positive when both variables tend to be above (or below) their means together.</p>` + ex(r`Gini coefficient and partisan polarization: 0.94.`)),
  K("con-corr-linear", ["correlation", "regression"], "4.2.2", 143, "Correlation coefficient (linear only)",
    r`The correlation coefficient quantifies the linear relationship between two variables. An upwards trend in the data cloud in a scatter plot implies a positive correlation, whereas a downwards trend in the data cloud represents a negative correlation. Correlation is often not suitable for representing a nonlinear relationship.`,
    r`<p>A correlation near 0 does <b>not</b> mean no relationship. The book's figure 4.3(d) shows a clear quadratic pattern with correlation 0.25. ±1 means the points lie on a single line.</p>`),
  K("con-assoc-causation", ["correlation", "causal"], "3.6.2", 103, "Association is not causation",
    "",
    r`<p>Two variables can move together because of a confounder or shared trends, not because one causes the other.</p>` + ex(r`Polarization and inequality both trended up (correlation 0.94), but so did life expectancy; trends alone don't show inequality caused polarization.`)),
  K("con-gini", ["correlation"], "3.6.2", 102, "Gini coefficient (and Lorenz curve)",
    r`The Gini coefficient (Gini index) measures the degree of income equality and inequality in a given society. It ranges from 0 (everyone has the same amount of wealth) to 1 (one person possesses all the wealth).`,
    r`<p>The <b>Lorenz curve</b> plots the cumulative share of income against the cumulative share of people, sorted from poorest to richest. The 45-degree line is perfect equality. Gini = A ÷ (A + B), where A is the area between the equality line and the Lorenz curve and B is the area under the curve.</p>`),
  K("con-kmeans", ["correlation"], "3.7.3", 111, "k-means algorithm",
    r`The k-means algorithm produces the prespecified number of clusters \(k\) and consists of the following steps: Step 1: Choose the initial centroids of \(k\) clusters. Step 2: Given the centroids, assign each observation to a cluster whose centroid is the closest (in terms of Euclidean distance) to that observation. Step 3: Choose the new centroid of each cluster whose coordinate equals the within-cluster mean of the corresponding variable. Step 4: Repeat Step 2 and 3 until cluster assignments no longer change.`,
    r`<p>The researcher chooses k and the starting centroids (random by default; use <code>nstart</code> to try several).</p>` + ex(r`With k = 2, the 112th Congress splits almost perfectly into Democrats and Republicans.`)),
  K("con-standardize", ["correlation"], "3.7.3", 112, "Standardizing inputs (centering and scaling)",
    "",
    r`<p>Converting variables to z-scores (subtract the mean = centering, divide by the SD = scaling) with <code>scale()</code>, so variables measured in different units count equally, e.g. before k-means. The book doesn't standardize DW-NOMINATE scores, because they are already on a meaningful common scale.</p>`),
  K("con-unsupervised", ["correlation"], "3.7.3", 115, "Unsupervised vs. supervised learning",
    "",
    r`<p><b>Unsupervised</b> learning (e.g. clustering) has no outcome variable; it looks for hidden structure. There's no clear measure of success, so human judgment is needed to decide whether results are reasonable. <b>Supervised</b> learning predicts an observed outcome.</p>`),

  // ---------- Prediction (4.1) ----------
  K("con-prediction-error", ["prediction"], "4.1.3", 133, "Prediction error",
    r`The prediction error is defined as prediction error = actual outcome − predicted outcome.`,
    r`<p>Positive error means the prediction was too low.</p>` + ex(r`Obama's actual state margin minus the poll-predicted margin.`)),
  K("con-bias", ["prediction"], "4.1.3", 133, "Bias (of a prediction)",
    r`The average prediction error is called bias, and prediction is said to be unbiased when its bias is zero.`,
    r`<p>Bias is about systematic over- or under-prediction <i>on average</i>; errors can be large yet cancel out.</p>` + ex(r`State polls had a bias of about 1.06 points: nearly unbiased.`)),
  K("con-rmse", ["prediction", "regression"], "4.1.3", 133, "Root-mean-squared error (RMSE)",
    r`The root mean square of prediction error is called root-mean-squared error, representing the average magnitude of prediction error.`,
    r`<p>RMSE measures accuracy for individual predictions regardless of sign. Small bias can coexist with large RMSE.</p>` + ex(r`State polls: bias ≈ 1.1 points but RMSE ≈ 5.9 points.`)),
  K("con-classification", ["prediction"], "4.1.3", 136, "Classification and misclassification",
    r`Classification refers to the problem of predicting a categorical outcome. Classification is either correct or incorrect. In a binary classification problem, there are two types of misclassification: false positive and false negative, representing incorrectly predicted positive and negative outcomes, respectively.`,
    r`<p>For winner-take-all elections, what matters is calling the right <i>winner</i>, not the exact margin.</p>`),
  K("con-confusion", ["prediction"], "4.1.3", 136, "False positive, false negative, confusion matrix",
    "",
    r`<p>A <b>confusion matrix</b> crosses predicted with actual outcomes: true positive, false positive (predicted positive, actually negative), false negative (predicted negative, actually positive), true negative.</p>` + ex(r`With an Obama win as "positive": Missouri was a false positive; Indiana and North Carolina were false negatives.`)),
  K("con-misclass-rate", ["prediction"], "4.1.3", 136, "Misclassification rate and the FP/FN trade-off",
    "",
    r`<p>Misclassification rate = share of cases predicted wrong (3/51 ≈ 6% for the 2008 state polls). There's a trade-off: making it harder to predict "positive" lowers false positives but raises false negatives, and vice versa.</p>`),

  // ---------- Linear regression ----------
  K("con-linear-model", ["regression"], "4.2.3", 144, "Linear regression model",
    r`The linear regression model is defined as \[Y = \alpha + \beta X + \epsilon,\] where \(Y\) is the outcome (or response) variable, \(X\) is the predictor or the independent (or explanatory) variable, \(\epsilon\) is the error (or disturbance) term, and \((\alpha, \beta)\) are the coefficients. The slope parameter \(\beta\) represents the increase in the average outcome associated with a one-unit increase in the predictor. Once the estimates of the coefficients \((\hat\alpha, \hat\beta)\) are obtained from the data, we can predict the outcome, using a given value of the predictor \(X = x\), as \(\hat{Y} = \hat\alpha + \hat\beta x\). The difference between the observed outcome and this fitted or predicted value \(\hat{Y}\) is called the residual and is denoted by \(\hat\epsilon = Y - \hat{Y}\).`,
    r`<p>A line describing how the average outcome changes with the predictor; the error term lets each observation deviate from the line.</p>`),
  K("con-intercept", ["regression"], "4.2.3", 143, "Intercept (α)",
    "",
    r`<p>The average value of Y when X = 0. It's often an extrapolation with no substantive meaning if X = 0 isn't in the data.</p>` + ex(r`−0.312: predicted Democratic margin when competence is 0 (−31.2 points).`)),
  K("con-slope", ["regression"], "4.2.3", 144, "Slope coefficient (β)",
    "",
    r`<p>The increase in the <b>average</b> outcome associated with a one-unit increase in X. Rescale to sensible units, e.g. for a 0.1 change multiply by 0.1. It is an association, not necessarily causal.</p>` + ex(r`0.660: a 0.1 increase in competence ↔ 6.6 points higher margin on average.`)),
  K("con-fitted", ["regression"], "4.2.3", 143, "Fitted (predicted) value",
    "",
    r`<p>\(\hat{Y} = \hat\alpha + \hat\beta x\): the regression line's prediction at a given X. <code>fitted(fit)</code> returns one for each observation used to fit the model; <code>predict()</code> computes them for new X values.</p>`),
  K("con-residual", ["regression"], "4.2.3", 143, "Residual",
    "",
    r`<p>\(\hat\epsilon = Y - \hat{Y}\): observed minus fitted, the regression's prediction error for each observation. Positive means the point lies above the line. <code>resid(fit)</code>.</p>`),
  K("con-resid-vs-error", ["regression"], "4.2.3", 143, "Residual vs. error term",
    "",
    r`<p>The <b>error term</b> \(\epsilon\) is part of the model and is unobserved; the <b>residual</b> \(\hat\epsilon\) is computed from data and is its estimate. Hats mark estimates: \(\alpha, \beta\) are parameters; \(\hat\alpha, \hat\beta\) are estimates.</p>`),
  K("con-least-squares", ["regression"], "4.2.3", 147, "Least squares",
    r`A common method of estimating the coefficients of the linear regression model is the method of least squares, which minimizes the sum of squared residuals, \[\text{SSR} = \sum_{i=1}^{n}\hat\epsilon_i^2 = \sum_{i=1}^{n}(Y_i - \hat\alpha - \hat\beta X_i)^2.\] The mean of residuals is always zero, and the regression line always goes through the center of data \((\bar{X}, \bar{Y})\) where \(\bar{X}\) and \(\bar{Y}\) are the sample means of \(X\) and \(Y\), respectively.`,
    r`<p>Choose the intercept and slope that make the squared vertical misses as small as possible: the "line of best fit."</p>`),
  K("con-ssr", ["regression"], "4.2.3", 146, "Sum of squared residuals (SSR)",
    "",
    r`<p>The total squared prediction error of the fitted line: \(\sum (Y_i - \hat{Y}_i)^2\). It plays two roles: least squares <b>minimizes</b> it, and model fit <b>compares</b> it with TSS. It's hard to interpret alone (squared units, grows with n); RMSE = \(\sqrt{\text{SSR}/n}\) puts it on the outcome's scale.</p>`),
  K("con-mean-resid-zero", ["regression"], "4.2.3", 147, "Mean of the residuals is zero",
    "",
    r`<p>With least squares and an intercept, the residuals always average exactly 0. This is an <b>algebraic fact that holds for any data</b>; it does not show the model is correct.</p>`),
  K("con-through-means", ["regression"], "4.2.3", 147, "The line passes through (x̄, ȳ)",
    "",
    r`<p>Because \(\hat\alpha = \bar{Y} - \hat\beta\bar{X}\), plugging \(X = \bar{X}\) into the fitted line gives \(\hat{Y} = \bar{Y}\). So the regression line always goes through the point of means.</p>`),
  K("con-slope-corr", ["regression", "correlation"], "4.2.3", 148, "Slope coefficient and correlation",
    r`The estimated slope coefficient from a linear regression model equals \(\rho\) standard deviation unit increase in the outcome variable that is associated with an increase of 1 standard deviation in the predictor, where \(\rho\) is the correlation between the two variables.`,
    r`<p>\(\hat\beta = \rho \times \frac{\text{SD of } Y}{\text{SD of } X}\). So the slope always has the same sign as the correlation.</p>` + ex(r`Correlation 0.43; SDs 0.19 (competence) and 0.29 (margin). A 0.19 increase in competence ↔ about 0.43 × 0.29 ≈ 13 points higher margin.`)),
  K("con-reg-flow", ["regression"], "4.2.3–4.2.6", 156, "Logical order of a simple linear regression analysis",
    "",
    r`<ol><li><b>Fit</b> by least squares: choose α̂, β̂ to minimize SSR (<code>lm()</code>).</li><li><b>Predict</b>: fitted values Ŷ = α̂ + β̂X and residuals Y − Ŷ.</li><li><b>Size of the misses</b>: SSR = Σ residual²; RMSE = √(SSR/n).</li><li><b>Benchmark</b>: TSS = Σ(Y − Ȳ)², the miss from predicting Ȳ for everyone (no X).</li><li><b>Fit</b>: R² = 1 − SSR/TSS.</li><li><b>Check</b>: residual plot for outliers; adjusted R² with several predictors; remember R² is in-sample.</li></ol>`),
  K("con-reg-rmse", ["regression"], "4.2.3", 146, "RMSE of a regression",
    "",
    r`<p>\(\text{RMSE} = \sqrt{\frac{1}{n}\text{SSR}} = \sqrt{\frac{1}{n}\sum\hat\epsilon_i^2}\): the average magnitude of the regression's prediction error, in the outcome's units. This is what least squares minimizes.</p>` + ex(r`Facial competence regression: RMSE ≈ 0.26, so a typical prediction misses by about 26 points.`)),
  K("con-tss", ["regression"], "4.2.6", 156, "Total sum of squares (TSS)",
    "",
    r`<p>\(\text{TSS} = \sum (Y_i - \bar{Y})^2\): the total variation of the outcome around its mean. It is the squared error you'd get predicting \(\bar{Y}\) for everyone, i.e. the SSR of a model with no predictor. It's the benchmark R² compares against.</p>`),
  K("con-r2", ["regression"], "4.2.6", 156, "Coefficient of determination (R²)",
    r`The coefficient of determination is a measure of model fit and represents the proportion of variation in the outcome variable explained by the predictor. It is defined as one minus the ratio of the sum of squared residuals (SSR) to the total sum of squares (TSS).`,
    r`<p>\(R^2 = \frac{\text{TSS} - \text{SSR}}{\text{TSS}} = 1 - \frac{\text{SSR}}{\text{TSS}}\).</p>` + ex(r`Perot 1996 votes explain 51% of the variation in Buchanan 2000 votes across Florida counties (85% without Palm Beach).`)),
  K("con-r2-range", ["regression"], "4.2.6", 156, "R² range and its link to correlation",
    "",
    r`<p>R² runs from 0 (correlation 0: X explains nothing) to 1 (correlation ±1: all points on the line). In simple regression, R² equals the correlation squared.</p>`),
  K("con-model-fit", ["regression"], "4.2.6", 155, "Model fit",
    "",
    r`<p>How well the model fits the data, i.e. how accurately it predicts the observations. Assessed with R², RMSE, and residual plots.</p>`),
  K("con-residual-plot", ["regression"], "4.2.6", 158, "Residual plot",
    "",
    r`<p>Residuals (y-axis) against fitted values (x-axis), with a line at 0. A good fit shows patternless scatter around 0. Look for outliers, curves (nonlinearity), or fanning spread.</p>` + ex(r`Florida: Palm Beach's residual (~2,000 extra Buchanan votes) stands far above the rest: the butterfly ballot.`)),
  K("con-outlier", ["regression"], "4.2.6", 159, "Outliers and influential observations",
    "",
    r`<p>An <b>outlier</b> has a very large residual. An <b>influential</b> observation noticeably moves the fitted line when included. One point can be both.</p>` + ex(r`Removing Palm Beach raises R² from 0.51 to 0.85 and shifts the regression line.`)),
  K("con-overfitting", ["regression"], "4.2.6", 161, "In-sample vs. out-of-sample fit; overfitting",
    "",
    r`<p>R² measures <b>in-sample</b> fit (the data used to fit the model). A model tailored too closely to one sample <b>overfits</b>: it captures idiosyncrasies and predicts worse in new data (<b>out-of-sample</b>). Adjusted R² is one guard.</p>`),
  K("con-all-models-wrong", ["regression"], "4.2.3", 143, "\"All models are wrong, but some are useful\"",
    "",
    r`<p>George Box's line, quoted in the book: the linear model is an approximation of the data-generating process. Even if the data aren't really linear, the model can still be useful for prediction.</p>`),
  K("con-reg-biased", ["regression"], "4.2.3", 147, "Can a linear regression be biased?",
    "",
    r`<p><b>As a predictor, in-sample: no.</b> With an intercept the residuals average exactly 0, so the prediction bias is 0 for any data. <b>As an estimate of a causal effect: yes</b>, if X is related to unobserved factors in the error term (confounding). Ch 7 calls the needed condition the exogeneity assumption.</p>`),
  K("con-rtm", ["regression"], "4.2.4", 149, "Regression towards the mean",
    r`Regression towards the mean represents an empirical phenomenon where an observation with a value of the predictor further away from the distribution's mean tends to have a value of an outcome variable closer to that mean. This tendency can be explained by chance alone.`,
    r`<p>Extreme values partly reflect luck that doesn't repeat.</p>` + ex(r`Obama did better in 2012 than in 2008 in 57% of bottom-quartile states (standardized vote shares) but only 46% of top-quartile states. Galton: tall parents' children tend to be shorter than their parents.`)),
  K("con-rtm-misread", ["regression"], "4.2.4", 149, "Common misreading of regression towards the mean",
    "",
    r`<p>It does <b>not</b> mean everyone converges to the same value over time (heights aren't converging). And a decline after an extreme value needn't reflect lost effort: students who ace the midterm tend to do less well on the final by chance alone. It holds technically when both variables are standardized.</p>`),
  K("con-multiple-reg", ["regression"], "4.3.2", 170, "Linear regression with multiple predictors",
    r`The linear regression model with multiple predictors is defined as \[Y = \alpha + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p + \epsilon,\] where the coefficient \(\beta_j\) represents the increase in the average outcome associated with a one-unit increase in \(X_j\) while holding the other variables constant. The coefficients are estimated by minimizing the sum of squared residuals. The degrees of freedom adjustment is often made when computing the coefficient of determination.`,
    r`<p>Each slope is a partial, "holding the others constant" association.</p>`),
  K("con-ceteris-paribus", ["regression"], "4.3.2", 165, "Ceteris paribus",
    "",
    r`<p>"All else equal": in multiple regression, \(\beta_j\) is the change in the average outcome for a one-unit increase in \(X_j\) <b>holding the other predictors constant</b>. Least squares always gives the best-fitting plane, but predictions rely on the linearity assumption.</p>`),
  K("con-adj-r2", ["regression"], "4.3.2", 169, "Adjusted R²",
    "",
    r`<p>\(1 - \frac{\text{SSR}/(n - p - 1)}{\text{TSS}/(n - 1)}\): R² with a degrees-of-freedom penalty for each predictor, so it can fall when a useless predictor is added. It's close to R² when n is large relative to p. R: <code>summary(fit)$adj.r.squared</code>.</p>`),
  K("con-df", ["regression", "inference"], "4.3.2", 169, "Degrees of freedom",
    "",
    r`<p>Roughly, the number of observations "free to vary": n minus the number of parameters estimated. With p predictors plus an intercept: n − p − 1. SSR is divided by n − p − 1; TSS by n − 1 (one parameter, the mean).</p>` + ex(r`The women regression: 322 villages − 2 coefficients = 320 df.`)),
  K("con-r2-never-decreases", ["regression"], "4.3.2", 169, "Why plain R² never decreases",
    "",
    r`<p>Adding any predictor, even pure noise, can only lower (or keep) SSR, so unadjusted R² never goes down. That's why it can't be used to decide whether a predictor belongs; adjusted R² penalizes extra predictors.</p>`),

  // ---------- Regression and causation (4.3) ----------
  K("con-reg-not-causal", ["regcausal"], "4.3", 161, "Regression and causation",
    "",
    r`<p>Causal inference requires predicting <b>counterfactual</b> outcomes. Regression captures association, which is causal only under the right design: randomized treatment, or a credible design such as RD. Otherwise confounders can drive the slope.</p>`),
  K("con-binary-treatment", ["regcausal"], "4.3.1", 165, "Regression on a binary treatment",
    r`When applied to experimental data with a single, binary treatment, the estimated slope coefficient of the linear regression model can be interpreted as an estimate of average treatment effect and is numerically equivalent to the difference-in-means estimator. The estimated intercept, on the other hand, is equal to the estimated average outcome under the control condition. The randomization of treatment assignment permits this causal interpretation of association identified under a linear regression model.`,
    r`<p>\(\hat\alpha\) = control mean (\(\hat Y(0)\)); \(\hat\beta\) = treated mean − control mean.</p>` + ex(r`<code>lm(water ~ reserved)</code>: intercept 14.738 (unreserved mean), slope 9.252 = difference in means.`)),
  K("con-factor-dummies", ["regcausal"], "4.3.2", 166, "Factor treatment: dummies and the base level",
    "",
    r`<p><code>lm()</code> turns a factor into indicator (dummy) variables and drops the <b>base level</b> (first alphabetically), because with an intercept all indicators would be redundant. Coefficients are differences from the base; intercept + coefficient = that group's mean. With <code>-1</code> (no intercept) each coefficient is a group mean. Effects between two groups are differences of coefficients under either version.</p>`),
  K("con-interaction", ["regcausal"], "4.3.3", 172, "Interaction term",
    r`An example of a linear regression model with an interaction term is \[Y = \alpha + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_1 X_2 + \epsilon.\] The model assumes that the effect of \(X_1\) linearly depends on \(X_2\). That is, as we increase \(X_2\) by one unit, the change in the average outcome associated with a one-unit increase of \(X_1\) goes up by \(\beta_3\).`,
    r`<p>The effect of \(X_1\) is \(\beta_1 + \beta_3 X_2\). Always include the main effects with the interaction (<code>x1 * x2</code> in R).</p>`),
  K("con-het-effects", ["regcausal"], "4.3.3", 170, "Heterogeneous treatment effects",
    "",
    r`<p>The treatment effect differs across kinds of units, so even a positive average effect may be zero or negative for some. Explore with subgroup differences-in-means or interaction terms; both give the same answer for a binary moderator.</p>` + ex(r`The Neighbors message raised turnout 9.7 points among 2004 voters vs 6.9 among non-voters (difference 2.7).`)),
  K("con-continuous-moderator", ["regcausal"], "4.3.3", 173, "Continuous moderator (e.g. age)",
    "",
    r`<p>With \(Y = \alpha + \beta_1\text{age} + \beta_2 T + \beta_3(\text{age}\times T)\), the effect at age x is \(\beta_2 + \beta_3 x\); \(\beta_3\) is the change in the effect per year of age. This adds a stronger linearity assumption.</p>` + ex(r`Neighbors effect estimated at 6.4 points at age 25 vs 10.2 at age 85.`)),
  K("con-quadratic", ["regcausal"], "4.3.3", 175, "Quadratic terms; interpret with predictions",
    "",
    r`<p>Adding \(\text{age}^2\) (<code>I(age^2)</code>) lets the relationship curve, e.g. turnout rising then falling with age. In complicated models, coefficients have no easy interpretation, so predict outcomes under each scenario with <code>predict()</code> and compare them.</p>` + ex(r`The estimated Neighbors effect peaks around age 60.`)),
  K("con-rd", ["regcausal"], "4.3.4", 181, "Regression discontinuity design (RD)",
    r`Regression discontinuity design (RD design) is a research design strategy for causal inference in observational studies with possible confounding factors. RD design assumes that the change in outcome at the point of discontinuity can be attributed to the change in the treatment variable alone. While RD design often has strong internal validity, it may lack external validity because the result may not be generalizable to observations away from the point of discontinuity.`,
    r`<p>Treatment switches on when a variable crosses a threshold. Units just above and just below are comparable, so fit a regression on each side and compare the predictions at the threshold.</p>` + ex(r`Tory MPs who barely won vs barely lost: being an MP almost doubled net wealth at death (~£255,000).`)),
  K("con-placebo", ["regcausal"], "4.3.4", 180, "Placebo test",
    "",
    r`<p>Estimate the "effect" on something the treatment <b>cannot</b> affect. A near-zero estimate supports the design; a large one suggests a violation (e.g. sorting or fraud near the threshold).</p>` + ex(r`Winning office can't change the party's margin in the <i>previous</i> election; the RD estimate there was −0.017, close to zero.`)),
  K("con-rd-local", ["regcausal"], "4.3.4", 181, "RD effects are local",
    "",
    r`<p>RD estimates the effect only for units near the threshold (e.g. candidates in close races). That gives strong internal but weaker external validity, since the effect may differ for landslide winners. RD needs weaker assumptions than other observational designs.</p>`),
  K("con-pred-vs-causal", ["regcausal", "prediction"], "4.4", 181, "Prediction vs. causation",
    "",
    r`<p>Prediction needs only association: forecast the observed outcome. Causal inference requires predicting <b>counterfactual</b> outcomes, which a good-fitting model of observed data doesn't guarantee. Causal inference is prediction of what would have happened.</p>`),

  // ---------- Regression output and inference (Ch 7) ----------
  K("inf-con-sampling-dist", ["inference"], "7.1.2", 323, "Sampling distribution",
    "",
    r`<p>The distribution of an estimate over hypothetically repeated samples (or repeated random treatment assignments). Each sample gives a different estimate; the sampling distribution describes how they vary. Unbiased means its mean equals the true value.</p>`),
  K("inf-con-se", ["inference"], "7.1.2", 324, "Standard error",
    r`To characterize the variability of an estimator, we can use the standard error, which is an estimated standard deviation of the sampling distribution.`,
    r`<p>How much an estimate would bounce around across repeated samples. Smaller = more precise. In <code>summary(lm)</code> it's the "Std. Error" column.</p>`),
  K("inf-con-t", ["inference"], "7.3.4", 381, "t-statistic (t value)",
    "",
    r`<p>Estimate ÷ standard error (for H₀: β = 0): how many standard errors the estimate is from 0. In regression it follows Student's t-distribution with n − p − 1 degrees of freedom under the null (n − 2 with one predictor). |t| ≳ 2 roughly corresponds to p &lt; 0.05.</p>` + ex(r`reserved: 9.252 / 3.948 = 2.344.`)),
  K("inf-con-pvalue", ["inference"], "7.2.2", 347, "p-value",
    "",
    r`<p>The book: "the probability that under the null hypothesis, we observe a value of the test statistic at least as extreme as the one we actually observed. A smaller p-value provides stronger evidence against the null hypothesis. Importantly, the p-value does not represent the probability that the null hypothesis is true."</p>`),
  K("inf-con-null", ["inference"], "7.2.2", 347, "Null hypothesis (H₀: β = 0)",
    "",
    r`<p>The hypothesis we try to refute (probabilistic proof by contradiction). In regression output, each row tests H₀: that coefficient = 0, i.e. no association / no effect. The alternative hypothesis is its complement (two-sided: β ≠ 0).</p>`),
  K("inf-con-alpha", ["inference"], "7.2.2", 347, "Level of the test (α) and statistical significance",
    "",
    r`<p>Reject H₀ if p ≤ α (commonly 0.05 or 0.01). α is the probability of rejecting a true null (Type I error). A result with p ≤ α is "statistically significant." Stars in R: *** &lt; 0.001, ** &lt; 0.01, * &lt; 0.05, . &lt; 0.1.</p>`),
  K("inf-con-reject", ["inference"], "7.2.2", 347, "Reject vs. \"fail to reject\" the null",
    "",
    r`<p>If p ≤ α, <b>reject</b> H₀. Otherwise <b>fail to reject</b> (retain) it. The book avoids "accept": failing to reject shows the data are consistent with H₀, not that H₀ is true.</p>` + ex(r`Minimum-wage NJ effect, p = 0.10: we fail to reject that the effect is zero.`)),
  K("inf-con-steps", ["inference"], "7.2.2", 349, "Steps of a hypothesis test",
    r`In general, statistical hypothesis testing consists of the following five steps: 1. Specify a null hypothesis and an alternative hypothesis. 2. Choose a test statistic and the level of test \(\alpha\). 3. Derive the reference distribution, which refers to the sampling distribution of the test statistic under the null hypothesis. 4. Compute the p-value, either one-sided or two-sided depending on the alternative hypothesis. 5. Reject the null hypothesis if the p-value is less than or equal to \(\alpha\). Otherwise, retain the null hypothesis (i.e., fail to reject the null hypothesis).`,
    r`<p>In <code>summary(lm)</code> all five happen for you: H₀: β = 0, test statistic = t value, reference distribution = t with n − p − 1 df, two-sided p-value = Pr(&gt;|t|).</p>`),
  K("inf-con-ci", ["inference"], "7.1.3", 327, "Confidence interval",
    "",
    r`<p>A range likely to contain the true value: estimate ± critical value × standard error (≈ ±1.96 SE for 95%). <b>Correct interpretation:</b> over hypothetically repeated samples, 95% of 95% intervals contain the truth. It is <i>not</i> "a 95% probability that this particular interval contains the truth" (that is 0 or 1). Higher confidence → wider interval. R: <code>confint(fit)</code>.</p>`),
  K("inf-con-ci-p", ["inference"], "7.3.4", 382, "Confidence intervals and p-values agree",
    "",
    r`<p>A 95% CI that excludes 0 corresponds to p &lt; 0.05 (reject H₀: β = 0). A CI that contains 0 corresponds to p &gt; 0.05.</p>` + ex(r`reserved: CI [1.49, 17.02], p = 0.02. NJ: CI [−0.011, 0.120], p = 0.10.`)),
  K("inf-con-type12", ["inference"], "7.2.2", 347, "Type I and Type II errors",
    "",
    r`<p><b>Type I</b>: rejecting a true null (false discovery); its probability is α, which you choose. <b>Type II</b>: retaining a false null (missed effect); it can't be controlled directly. Lowering one tends to raise the other.</p>`),
  K("inf-con-multiple", ["inference"], "7.2.5", 363, "Multiple testing",
    r`The multiple testing problem is that conducting many hypothesis tests is likely to result in false discoveries, i.e., incorrect rejection of null hypotheses.`,
    r`<p>With α = 0.05, testing 10 true nulls gives about a 40% chance of at least one false "significant" result (1 − 0.95¹⁰). Example: Paul the Octopus.</p>`),
  K("inf-con-significance", ["inference"], "7.2.2", 350, "Statistical vs. scientific significance",
    "",
    r`<p>A p-value measures how strongly the data contradict the null, not how <i>large</i> or important the effect is. Hypothesis testing can determine statistical significance but "often fails to provide a direct measure of scientific significance." Report the size of the estimate and its CI. (Related pitfall: publication bias toward p &lt; 0.05.)</p>`),
  K("inf-con-exogeneity", ["inference", "regcausal"], "7.3.1", 370, "Exogeneity assumption",
    r`The exogeneity assumption for the linear regression model is defined as \(E(\epsilon_i \mid X_1, X_2, \ldots, X_p) = E(\epsilon_i) = 0.\)`,
    r`<p>The unobserved determinants of the outcome (in the error term) must be unrelated to the predictors. It holds automatically when X is randomized; it's violated when there are unobserved confounders. Including measured confounders as predictors makes it more plausible.</p>`),
  K("inf-con-unbiased", ["inference", "regression"], "7.3.2", 377, "Unbiasedness of least-squares coefficients",
    r`Under the exogeneity assumption, the least squares estimates of the coefficients in the linear regression model are unbiased.`,
    r`<p>\(E(\hat\beta) = \beta\): over hypothetical repeated samples, the estimates average out to the true values. This is the formal answer to "can a regression be biased?": yes, if exogeneity fails (omitted confounders).</p>`),
  K("inf-con-t-df", ["inference"], "7.3.4", 381, "Why the t-distribution and n − p − 1 df",
    "",
    r`<p>R's p-values and CIs for coefficients use Student's t-distribution, which has thicker tails than the normal, giving slightly larger p-values and wider intervals (conservative). Its degrees of freedom are n minus the number of estimated coefficients: 322 − 2 = 320 in the women example; 358 − 7 = 351 in the minimum-wage model.</p>`),
];
