// Equation cards: the formula on the front; on the back, its name, what each symbol means, and what it measures.
const r = String.raw;
const E = (id, topics, sec, page, front, back) => ({ id, dict: "equation", topics, sec, page, front, back, reversible: true });

export default [
  E("eq-causal-effect", ["causal"], "2.3", 48, r`\(Y_i(1) - Y_i(0)\)`,
    r`<p><b>Individual causal effect.</b> \(i\) indexes a unit; \(Y_i(1)\) is its outcome under treatment (\(T_i = 1\)), \(Y_i(0)\) under control (\(T_i = 0\)). Only one of the two is ever observed.</p>`),
  E("eq-observed", ["causal"], "2.3", 48, r`\(Y_i = Y_i(T_i)\)`,
    r`<p><b>Observed outcome</b> (the fundamental problem, formally). The outcome we see is the potential outcome matching the unit's actual treatment status \(T_i\): \(Y_i(1)\) if treated, \(Y_i(0)\) if not.</p>`),
  E("eq-sate", ["causal"], "2.4.1", 49, r`\[\frac{1}{n}\sum_{i=1}^{n}\{Y_i(1) - Y_i(0)\}\]`,
    r`<p><b>SATE</b>: the sample average treatment effect. \(n\) = sample size; \(\sum_{i=1}^{n}\) adds over every unit from \(i = 1\) to \(n\); each term is one unit's causal effect. It's unobservable directly; estimated by the difference-in-means under randomization.</p>`),
  E("eq-satt", ["causal"], "2.5.3", 62, r`\[\frac{1}{n_1}\sum_{i=1}^{n} T_i\{Y_i(1) - Y_i(0)\}\]`,
    r`<p><b>SATT</b>: the average effect for the treated. \(T_i\) is the binary treatment indicator (1 if treated), so only treated units' effects are added; \(n_1 = \sum_{i=1}^{n} T_i\) is the number of treated units. Estimated by DiD.</p>`),
  E("eq-diff-means", ["causal"], "2.4.1", 49, r`\(\bar{Y}_{\text{treated}} - \bar{Y}_{\text{control}}\)`,
    r`<p><b>Difference-in-means estimator.</b> The mean outcome of the treatment group minus that of the control group. It estimates the SATE when treatment is randomized; it equals the slope in <code>lm(y ~ treat)</code>.</p>`),
  E("eq-did", ["causal"], "2.5.3", 62, r`\[(\bar{Y}^{\text{after}}_{\text{treated}} - \bar{Y}^{\text{before}}_{\text{treated}}) - (\bar{Y}^{\text{after}}_{\text{control}} - \bar{Y}^{\text{before}}_{\text{control}})\]`,
    r`<p><b>Difference-in-differences estimate</b> of the SATT. First bracket: the treated group's change over time. Second: the control group's change, the estimated trend without treatment. Assumes parallel trends.</p><p>Minimum wage: 0.024 − (−0.038) = 0.062.</p>`),
  E("eq-median", ["describe"], "2.6.1", 64, r`\[\text{median} = \begin{cases} x_{((n+1)/2)} & \text{if } n \text{ is odd} \\ \tfrac{1}{2}\left(x_{(n/2)} + x_{(n/2+1)}\right) & \text{if } n \text{ is even} \end{cases}\]`,
    r`<p><b>Median.</b> \(x_{(i)}\) is the \(i\)th smallest observation (sorted data); \(n\) is the sample size. Odd n: the middle value. Even n: the average of the two middle values. Median of {1, 3, 4, 10} = (3 + 4)/2 = 3.5.</p>`),
  E("eq-rms", ["describe"], "2.6.2", 66, r`\[\sqrt{\frac{1}{n}\sum_{i=1}^{n} x_i^2}\]`,
    r`<p><b>Root mean square (RMS).</b> Square each entry \(x_i\), take the mean over \(n\) entries, then the square root: the average magnitude of the entries, ignoring sign.</p>`),
  E("eq-sd", ["describe"], "2.6.2", 68, r`\[\sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2} \quad\text{or}\quad \sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2}\]`,
    r`<p><b>Standard deviation</b>: the RMS of deviations from the mean. \(x_i\) = each value, \(\bar{x}\) = the sample mean, \(n\) = sample size. The \(n - 1\) version is what R's <code>sd()</code> uses; the difference is minor with enough data.</p>`),
  E("eq-variance", ["describe"], "2.6.2", 68, r`\[\frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2\]`,
    r`<p><b>Variance</b>: the square of the standard deviation, the average squared deviation from the mean (here the \(n - 1\) version, as in R's <code>var()</code>). Its units are squared, so it's harder to interpret.</p>`),
  E("eq-density", ["describe"], "3.3.2", 82, r`\[\text{density} = \frac{\text{proportion of observations in the bin}}{\text{width of the bin}}\]`,
    r`<p><b>Histogram density</b>: the height of a bin. Because height × width = proportion, each bin's <i>area</i> is the share of observations in it, and the areas sum to 1. Density is "proportion per unit of x" and can exceed 1.</p>`),
  E("eq-log", ["sampling"], "3.4.1", 92, r`\(y = \log_e x \;\Longleftrightarrow\; x = e^{y}\)`,
    r`<p><b>Natural logarithm</b>: \(e \approx 2.718\) is the base. Generally \(y = \log_b x \Leftrightarrow x = b^y\) (e.g. \(\log_{10} 1000 = 3\)). The log is the inverse of the exponential function; it's defined only for \(x &gt; 0\). R: <code>log()</code> and <code>exp()</code>.</p>`),
  E("eq-list-exp", ["sampling"], "3.4.2", 95, r`\(\overline{\text{count}}_{\text{treatment list}} - \overline{\text{count}}_{\text{control list}}\)`,
    r`<p><b>List experiment estimate</b>: the treatment group's list has one extra (sensitive) item, so the difference in average item counts estimates the proportion for whom the sensitive item is true (≈ 0.05 support for the ISAF).</p>`),
  E("eq-gini", ["correlation"], "3.6.2", 102, r`\[\text{Gini} = \frac{A}{A + B}\]`,
    r`<p><b>Gini coefficient.</b> A = area between the 45° line of equality and the Lorenz curve; B = area under the Lorenz curve (A + B is the area under the line of equality). 0 = perfect equality; 1 = one person has everything.</p>`),
  E("eq-zscore", ["correlation"], "3.6.2", 104, r`\[\frac{x_i - \bar{x}}{S_x}\]`,
    r`<p><b>z-score</b> of observation \(x_i\). \(\bar{x}\) = mean, \(S_x\) = standard deviation of x. The number of SDs \(x_i\) lies above (+) or below (−) the mean; it doesn't change if x is rescaled or shifted.</p>`),
  E("eq-correlation", ["correlation"], "3.6.2", 105, r`\[\frac{1}{n}\sum_{i=1}^{n}\frac{x_i - \bar{x}}{S_x}\times\frac{y_i - \bar{y}}{S_y}\]`,
    r`<p><b>Correlation</b>: the average product of the two variables' z-scores. \(\bar{x}, \bar{y}\) = means; \(S_x, S_y\) = SDs. Between −1 and 1; positive when x and y tend to be above their means together. (Using \(n - 1\) throughout gives the same value.)</p>`),
  E("eq-pred-error", ["prediction"], "4.1.3", 133, r`\(\text{actual outcome} - \text{predicted outcome}\)`,
    r`<p><b>Prediction error.</b> Positive means the prediction was too low. For a regression this is the residual \(Y - \hat{Y}\).</p>`),
  E("eq-bias", ["prediction"], "4.1.3", 133, r`\[\frac{1}{n}\sum_{i=1}^{n}(\text{actual}_i - \text{predicted}_i)\]`,
    r`<p><b>Bias</b>: the mean prediction error. Zero means unbiased: errors cancel out on average, even if individual errors are large.</p>`),
  E("eq-rmse", ["prediction", "regression"], "4.1.3", 133, r`\[\sqrt{\frac{1}{n}\sum_{i=1}^{n}(\text{prediction error}_i)^2}\]`,
    r`<p><b>RMSE</b> (root-mean-squared error): the RMS of prediction errors, i.e. their average magnitude. For a regression, \(\sqrt{\text{SSR}/n}\).</p>`),
  E("eq-linear-model", ["regression"], "4.2.3", 144, r`\(Y = \alpha + \beta X + \epsilon\)`,
    r`<p><b>Linear regression model.</b> \(Y\) = outcome; \(X\) = predictor; \(\alpha\) = intercept (average Y when X = 0); \(\beta\) = slope (change in average Y per one-unit increase in X); \(\epsilon\) = error term (unobserved deviation from the line).</p>`),
  E("eq-fitted-resid", ["regression"], "4.2.3", 143, r`\(\hat{Y} = \hat\alpha + \hat\beta x, \qquad \hat\epsilon = Y - \hat{Y}\)`,
    r`<p><b>Fitted value and residual.</b> Hats mark estimates. \(\hat{Y}\) is the line's prediction at \(X = x\); the residual \(\hat\epsilon\) is observed minus fitted. R: <code>fitted()</code>, <code>resid()</code>.</p>`),
  E("eq-ssr", ["regression"], "4.2.3", 146, r`\[\text{SSR} = \sum_{i=1}^{n}\hat\epsilon_i^2 = \sum_{i=1}^{n}(Y_i - \hat\alpha - \hat\beta X_i)^2\]`,
    r`<p><b>Sum of squared residuals.</b> The quantity least squares minimizes over \(\hat\alpha, \hat\beta\); also the numerator of 1 − R². \(Y_i, X_i\) = each observation's outcome and predictor.</p>`),
  E("eq-ls", ["regression"], "4.2.3", 146, r`\[\hat\alpha = \bar{Y} - \hat\beta\bar{X}, \qquad \hat\beta = \frac{\sum_{i=1}^{n}(Y_i - \bar{Y})(X_i - \bar{X})}{\sum_{i=1}^{n}(X_i - \bar{X})^2}\]`,
    r`<p><b>Least-squares intercept and slope.</b> \(\bar{X}, \bar{Y}\) = sample means. The slope is the co-movement of X and Y divided by the spread of X. The intercept formula forces the line through \((\bar{X}, \bar{Y})\).</p>`),
  E("eq-slope-corr", ["regression", "correlation"], "4.2.3", 147, r`\[\hat\beta = \rho \times \frac{\text{SD of } Y}{\text{SD of } X}\]`,
    r`<p><b>Slope in terms of correlation.</b> \(\rho\) = correlation of X and Y. A 1-SD increase in X goes with a \(\rho\)-SD increase in Y; the slope always has the sign of the correlation. With standardized variables, the slope equals \(\rho\).</p>`),
  E("eq-tss", ["regression"], "4.2.6", 156, r`\[\text{TSS} = \sum_{i=1}^{n}(Y_i - \bar{Y})^2\]`,
    r`<p><b>Total sum of squares.</b> Total variation of the outcome around its mean \(\bar{Y}\): the squared error from predicting \(\bar{Y}\) for everyone (no predictor).</p>`),
  E("eq-r2", ["regression"], "4.2.6", 156, r`\[R^2 = \frac{\text{TSS} - \text{SSR}}{\text{TSS}} = 1 - \frac{\text{SSR}}{\text{TSS}}\]`,
    r`<p><b>Coefficient of determination.</b> The share of the outcome's variation (TSS) explained by the model: the fraction by which using X shrinks the squared error. 0 to 1; equals \(\rho^2\) in simple regression.</p>`),
  E("eq-adj-r2", ["regression"], "4.3.2", 169, r`\[\text{adjusted } R^2 = 1 - \frac{\text{SSR}/(n - p - 1)}{\text{TSS}/(n - 1)}\]`,
    r`<p><b>Adjusted R².</b> \(n\) = observations; \(p\) = number of predictors, so \(p + 1\) coefficients including the intercept. SSR is divided by its degrees of freedom \(n - p - 1\); TSS by \(n - 1\) (only the mean is estimated). Penalizes adding predictors.</p>`),
  E("eq-multiple", ["regression"], "4.3.2", 170, r`\(Y = \alpha + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p + \epsilon\)`,
    r`<p><b>Multiple regression model.</b> \(p\) predictors; \(\beta_j\) = change in average Y for a one-unit increase in \(X_j\), <i>holding the other predictors constant</i>. Coefficients are estimated by least squares.</p>`),
  E("eq-interaction", ["regcausal"], "4.3.3", 171, r`\[\frac{\partial Y}{\partial X_1} = \beta_1 + \beta_3 X_2 \quad\text{in}\quad Y = \alpha + \beta_1X_1 + \beta_2X_2 + \beta_3X_1X_2 + \epsilon\]`,
    r`<p><b>Conditional effect in an interaction model.</b> The effect of a one-unit increase in \(X_1\) depends on \(X_2\): it's \(\beta_1\) when \(X_2 = 0\) and grows by \(\beta_3\) per unit of \(X_2\). For a binary \(X_2\): \(\beta_1\) in one group, \(\beta_1 + \beta_3\) in the other.</p>`),
  E("eq-binary-reg", ["regcausal"], "4.3.1", 164, r`\[\hat\alpha = \frac{1}{n_0}\sum_{i=1}^{n}(1 - X_i)Y_i, \qquad \hat\beta = \frac{1}{n_1}\sum_{i=1}^{n}X_iY_i - \frac{1}{n_0}\sum_{i=1}^{n}(1 - X_i)Y_i\]`,
    r`<p><b>Regression on a binary predictor.</b> \(X_i \in \{0, 1\}\); \(n_1 = \sum X_i\) treated units, \(n_0 = n - n_1\) controls. \(\hat\alpha\) = control mean; \(\hat\beta\) = treated mean − control mean (the difference-in-means).</p>`),
  E("eq-tstat", ["inference"], "7.3.4", 380, r`\[t = \frac{\hat\beta - 0}{\text{standard error of } \hat\beta}\]`,
    r`<p><b>t-statistic</b> for H₀: β = 0 (the "t value" column). How many standard errors the estimate lies from 0. Compared with Student's t-distribution with \(n - p - 1\) degrees of freedom to get the p-value.</p>`),
  E("eq-ci", ["inference"], "7.3.4", 380, r`\[\left[\hat\beta - z_{\alpha/2}\times \text{SE},\;\; \hat\beta + z_{\alpha/2}\times \text{SE}\right]\]`,
    r`<p><b>\((1 - \alpha)\times 100\%\) confidence interval.</b> SE = standard error; \(z_{\alpha/2}\) = critical value (1.96 for 95%, α = 0.05). A larger confidence level means a larger critical value and a wider interval. R's <code>confint()</code> uses the slightly larger t critical value.</p>`),
  E("eq-rse", ["inference", "regression"], "7.3.4", 383, r`\[\text{residual standard error} = \sqrt{\frac{\text{SSR}}{n - p - 1}}\]`,
    r`<p><b>Residual standard error</b> (in <code>summary(lm)</code>): the standard deviation of the residuals using the degrees of freedom \(n - p - 1\): the typical size of a residual, in Y's units. Compare RMSE, which divides by \(n\).</p>`),
];
