// Coverage map: every line of the study guide (POLS_7012 MIDTERM STUDY GUIDES.docx) -> the cards that teach it.
// build_flash.mjs fails if any item has no card or names a card that doesn't exist.
const g = (dict, item, ...cards) => ({ dict, item, cards });

export default [
  // Commands Dictionary
  g("Commands", "Data structures: c(), seq(), rep(), :, length(), names(), matrix(), list(), data.frame()", "cmd-c", "cmd-seq", "cmd-rep", "cmd-length-names", "cmd-matrix", "cmd-list"),
  g("Commands", "Inspecting data: head(), dim(), nrow(), ncol(), summary(), class()", "cmd-head", "cmd-dim", "cmd-summary", "cmd-class"),
  g("Commands", "Indexing and subsetting: $, [ ], [ , ], [[ ]], subset()", "cmd-index", "cmd-dataframe-index", "cmd-list", "cmd-subset", "cmd-logical-index"),
  g("Commands", "Relational operators: <, >, <=, >=, ==, !=", "cmd-relational"),
  g("Commands", "Logical operators: & (and), | (or)", "cmd-logical"),
  g("Commands", "ifelse()", "cmd-ifelse"),
  g("Commands", "Factors: as.factor(), levels()", "cmd-factor", "cmd-factor-base"),
  g("Commands", "Tables: table(), prop.table(), addmargins()", "cmd-table", "cmd-addmargins", "cmd-table-rates", "cmd-proptable"),
  g("Commands", "tapply()", "cmd-tapply"),
  g("Commands", "Summary statistics: mean(), median(), sd(), var(), quantile(), IQR(), min(), max(), range(), sum()", "cmd-mean-median", "cmd-sd-var", "cmd-quantile", "cmd-logical"),
  g("Commands", "Missing data: NA, is.na(), na.rm = TRUE, na.omit(), exclude = NULL", "cmd-isna", "cmd-narm", "cmd-naomit", "cmd-exclude"),
  g("Commands", "Transformations: log(), exp(), scale()", "cmd-log", "cmd-scale"),
  g("Commands", "cor()", "cmd-cor"),
  g("Commands", "lm()", "cmd-lm"),
  g("Commands", "lm formula syntax: y ~ x, +, :, *, -1, I()", "cmd-factor-base", "cmd-interaction", "cmd-noint", "cmd-iwrap"),
  g("Commands", "lm output: coef(), fitted(), resid(), predict(newdata = ), summary(fit)$r.squared, $adj.r.squared", "cmd-coef-fitted", "cmd-predict", "cmd-rsq"),
  g("Commands", "Factor predictors: the base (reference) level is the first level alphabetically", "cmd-factor-base", "inf-multi-base"),
  g("Commands", "merge() vs cbind()", "cmd-merge"),
  g("Commands", "kmeans() and its output ($cluster, $centers, $size, $iter)", "cmd-kmeans"),
  g("Commands", "apply(), rowMeans(), colSums()", "cmd-matrix"),
  g("Commands", "Loops and conditionals: for (i in 1:n) { }, if () { } else { }, %%, cat()", "cmd-for", "cmd-if", "cmd-modulo"),
  g("Commands", "sign() (finding misclassified units)", "cmd-sign"),
  g("Commands", "Plot building: abline(), lines(), points(), text(), par(mfrow = ), pdf() and dev.off()", "cmd-plot-layers", "cmd-par"),
  g("Commands", "(added) Reading summary(lm): t values, p values, simple and multiple regression", "inf-summary-overview", "inf-estimate-se", "inf-tvalue", "inf-pvalue", "inf-intercept-row", "inf-model-lines", "inf-confint", "inf-summary-continuous", "inf-summary-multi", "inf-multi-other", "inf-multi-base", "inf-multi-fit", "inf-confint-multi"),

  // Concepts Dictionary
  g("Concepts", "Experimental Research", "con-experimental"),
  g("Concepts", "Causal Effect", "con-causal-effect"),
  g("Concepts", "Counterfactual and potential outcomes, Y(1) and Y(0)", "con-potential-outcomes"),
  g("Concepts", "Fundamental Problem of Causal Inference", "con-fundamental"),
  g("Concepts", "Immutable characteristics and \"no causation without manipulation\"", "con-immutable"),
  g("Concepts", "Sample Average Treatment Effect (SATE)", "con-sate"),
  g("Concepts", "Sample Average Treatment Effect for the Treated (SATT)", "con-satt"),
  g("Concepts", "Difference-in-Means Estimator", "con-diff-means"),
  g("Concepts", "Randomized Controlled Trial", "con-rct"),
  g("Concepts", "Balance check", "con-balance"),
  g("Concepts", "Internal Validity", "con-internal"),
  g("Concepts", "External Validity", "con-external"),
  g("Concepts", "Hawthorne Effect", "con-hawthorne"),
  g("Concepts", "Observational study", "con-observational"),
  g("Concepts", "Confounder and Confounding Bias", "con-confounder"),
  g("Concepts", "Selection bias (self-selection into treatment)", "con-selection-bias"),
  g("Concepts", "Statistical Control", "con-statistical-control"),
  g("Concepts", "Subclassification", "con-subclassification"),
  g("Concepts", "Cross-section comparison design", "con-cross-section"),
  g("Concepts", "Before-and-After Design", "con-before-after"),
  g("Concepts", "Difference-in-Differences Design", "con-did"),
  g("Concepts", "Parallel trends assumption", "con-parallel-trends"),
  g("Concepts", "Mean and Median (the mean is sensitive to outliers; the median is robust)", "con-median"),
  g("Concepts", "Quantiles", "con-quantiles"),
  g("Concepts", "Quartiles", "con-quartiles"),
  g("Concepts", "IQR", "con-iqr"),
  g("Concepts", "Root Mean Square (RMS)", "con-rms"),
  g("Concepts", "Standard Deviation", "con-sd"),
  g("Concepts", "Variance", "con-variance"),
  g("Concepts", "Density (histogram)", "con-density"),
  g("Concepts", "Survey sampling: population vs. sample, census, sampling frame", "con-survey-sampling", "con-sampling-frame"),
  g("Concepts", "Simple Random Sampling", "con-srs"),
  g("Concepts", "Probability Sampling", "con-probability-sampling"),
  g("Concepts", "Quota sampling (and why it fails)", "con-quota"),
  g("Concepts", "Multistage cluster sampling", "con-cluster"),
  g("Concepts", "Sample Selection Bias", "con-sample-selection-bias"),
  g("Concepts", "Natural Logarithmic Transformation", "con-log"),
  g("Concepts", "Unit Nonresponse", "con-unit-nonresponse"),
  g("Concepts", "Item Nonresponse", "con-item-nonresponse"),
  g("Concepts", "Missing data and listwise deletion", "con-listwise"),
  g("Concepts", "Social desirability bias", "con-social-desirability"),
  g("Concepts", "List experiment (item count technique); floor and ceiling effects", "con-list-experiment", "con-floor-ceiling"),
  g("Concepts", "Randomized response technique", "con-randomized-response"),
  g("Concepts", "Latent concepts and measurement models (ideal points, spatial voting, item response theory)", "con-latent", "con-ideal-point", "con-irt"),
  g("Concepts", "Gini Coefficient (and the Lorenz curve)", "con-gini"),
  g("Concepts", "Z-score", "con-zscore"),
  g("Concepts", "Binary (dummy) variables: the mean of a 0/1 variable is the proportion of 1s", "con-binary-mean"),
  g("Concepts", "Percent vs. percentage points", "con-pct-points"),
  g("Concepts", "Correlation, and why association is not causation", "con-correlation", "con-assoc-causation"),
  g("Concepts", "k-means clustering, standardizing inputs, unsupervised learning", "con-kmeans", "con-standardize", "con-unsupervised"),
  g("Concepts", "Prediction Error", "con-prediction-error"),
  g("Concepts", "Bias", "con-bias"),
  g("Concepts", "RMSE", "con-rmse"),
  g("Concepts", "Classification and Misclassification", "con-classification"),
  g("Concepts", "False positive, false negative, confusion matrix, misclassification rate", "con-confusion", "con-misclass-rate"),
  g("Concepts", "Correlation Coefficient (linear relationships only)", "con-corr-linear"),
  g("Concepts", "Simple Linear Regression Model", "con-linear-model", "con-intercept", "con-slope", "con-fitted", "con-residual", "con-resid-vs-error"),
  g("Concepts", "Logical order: least squares -> fitted values and residuals -> SSR and RMSE -> TSS -> R^2 -> residual plot", "con-reg-flow", "con-least-squares", "con-ssr", "con-reg-rmse", "con-tss", "con-r2"),
  g("Concepts", "Least squares: mean residual is 0; line passes through the means", "con-mean-resid-zero", "con-through-means"),
  g("Concepts", "Can linear regressions be biased?", "con-reg-biased", "inf-con-exogeneity", "inf-con-unbiased"),
  g("Concepts", "Linear Regression Model with Multiple Predictors (ceteris paribus)", "con-multiple-reg", "con-ceteris-paribus"),
  g("Concepts", "Residuals", "con-residual"),
  g("Concepts", "Residual plot, outliers, influential observations", "con-residual-plot", "con-outlier"),
  g("Concepts", "Slope Coefficient (slope = correlation x SD of Y / SD of X)", "con-slope", "con-slope-corr"),
  g("Concepts", "Intercept", "con-intercept"),
  g("Concepts", "Regression Towards the Mean", "con-rtm", "con-rtm-misread"),
  g("Concepts", "Coefficient of Determination (R^2)", "con-r2", "con-r2-range", "con-model-fit"),
  g("Concepts", "Adjusted R^2 and degrees of freedom", "con-adj-r2", "con-df", "con-r2-never-decreases"),
  g("Concepts", "In-sample vs. out-of-sample fit; overfitting", "con-overfitting", "con-all-models-wrong"),
  g("Concepts", "Regression on a Binary Treatment (slope = difference-in-means; intercept = control-group mean)", "con-binary-treatment", "con-factor-dummies"),
  g("Concepts", "Interaction Term", "con-interaction", "con-continuous-moderator", "con-quadratic"),
  g("Concepts", "Heterogeneous Treatment Effect", "con-het-effects"),
  g("Concepts", "Regression Discontinuity Design", "con-rd"),
  g("Concepts", "Placebo test; the effect is local to the threshold", "con-placebo", "con-rd-local"),
  g("Concepts", "Prediction vs. causation", "con-pred-vs-causal", "con-reg-not-causal"),
  g("Concepts", "(added) t values, p values, and inference for regression (Ch 7)", "inf-con-sampling-dist", "inf-con-se", "inf-con-t", "inf-con-pvalue", "inf-con-null", "inf-con-alpha", "inf-con-reject", "inf-con-steps", "inf-con-ci", "inf-con-ci-p", "inf-con-type12", "inf-con-multiple", "inf-con-significance", "inf-con-t-df"),

  // Equation Dictionary
  g("Equations", "Individual causal effect: Yi(1) - Yi(0)", "eq-causal-effect", "eq-observed"),
  g("Equations", "Sample Average Treatment Effect", "eq-sate"),
  g("Equations", "Sample Average Treatment Effect for the Treated", "eq-satt"),
  g("Equations", "Difference-in-means", "eq-diff-means"),
  g("Equations", "Difference-in-differences estimate", "eq-did"),
  g("Equations", "Median (n odd vs. n even)", "eq-median"),
  g("Equations", "Root Mean Square", "eq-rms"),
  g("Equations", "Standard Deviation (n and n - 1 versions)", "eq-sd"),
  g("Equations", "Variance", "eq-variance"),
  g("Equations", "Density = proportion in the bin / bin width", "eq-density"),
  g("Equations", "Natural log: y = log_e(x) <-> x = e^y", "eq-log"),
  g("Equations", "List experiment estimate (difference in mean counts)", "eq-list-exp"),
  g("Equations", "Gini = A / (A + B)", "eq-gini"),
  g("Equations", "Z-score", "eq-zscore"),
  g("Equations", "Correlation", "eq-correlation"),
  g("Equations", "Prediction error = actual - predicted", "eq-pred-error"),
  g("Equations", "Bias = mean of the prediction errors", "eq-bias"),
  g("Equations", "RMSE", "eq-rmse"),
  g("Equations", "Linear Model: Y = alpha + beta X + epsilon", "eq-linear-model"),
  g("Equations", "Fitted value and residual", "eq-fitted-resid"),
  g("Equations", "SSR (sum of squared residuals)", "eq-ssr"),
  g("Equations", "Least squares intercept and slope", "eq-ls"),
  g("Equations", "Slope = correlation x (SD of Y / SD of X)", "eq-slope-corr"),
  g("Equations", "TSS (total sum of squares)", "eq-tss"),
  g("Equations", "R^2 = 1 - SSR/TSS", "eq-r2"),
  g("Equations", "Adjusted R^2", "eq-adj-r2"),
  g("Equations", "Multiple regression model", "eq-multiple"),
  g("Equations", "Interaction model and the conditional effect: beta1 + beta3 X2", "eq-interaction"),
  g("Equations", "(added) Binary-predictor intercept and slope; t-statistic; confidence interval; residual standard error", "eq-binary-reg", "eq-tstat", "eq-ci", "eq-rse"),

  // Graphs Dictionary
  g("Graphs", "Bar Graph", "gr-bar"),
  g("Graphs", "Histogram (density vs. frequency; choosing breaks)", "gr-hist", "cmd-plot-layers"),
  g("Graphs", "Scatter Plot", "gr-scatter"),
  g("Graphs", "Box Plot (box, median, whiskers at 1.5 x IQR, outliers as circles)", "gr-box"),
  g("Graphs", "Line Graph (time series, type = \"l\")", "gr-line"),
  g("Graphs", "Quantile-Quantile Plot", "gr-qq"),
  g("Graphs", "Residual Plot (residuals vs. fitted values)", "gr-residual"),
  g("Graphs", "Lorenz Curve (behind the Gini coefficient)", "gr-lorenz"),
  g("Graphs", "Difference-in-Differences Figure (counterfactual line and treatment effect)", "gr-did"),
];
